using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Net.Mime;
using System.Text;
using System.Threading.Tasks;

namespace GenericWithIdentityModel.Notification
{
    public class EmailService : IEmailService
    {
        public void SendEmail(string to, string subject, string body, EmailPriority priority = EmailPriority.Normal, string attachmentURL = "", string name = "")
        {
            //tv : get email confirmations
            var displayName = "ApplicationName";
            var from = "noreply@yuktisolutions.com";

            var sender = new MailAddress(from, displayName, System.Text.Encoding.UTF8);
            var mainReceiver = new MailAddress(to);

            var msg = new MailMessage(sender, mainReceiver);



            try
            {
                if (!string.IsNullOrEmpty(attachmentURL))
                {
                    Attachment attachment = new System.Net.Mail.Attachment(attachmentURL);
                    msg.Attachments.Add(attachment);
                }
            }
            catch (Exception ex)
            {
                //todo: write a log if attachement thrown an exceoption
            }


            msg.Subject = $"ApplicationName :{subject}";
            msg.IsBodyHtml = true;

           // var emailTemplate = File.ReadAllText($"{Environment.CurrentDirectory}/wwwroot/EmailTemplates/DefaultTemplate.html");
            //msg.Body = emailTemplate
            //            .Replace("###RECEIVER###", $" Dear {(string.IsNullOrEmpty(name) ? to : name)}")
            //            .Replace("###BESTREGARDS###", "BESTREGARDS")
            //            .Replace("###TEAM###", $" TEAM ApplicationName")
            //            .Replace("###AUTOGENERATEDMESSAGE###", "AUTOGENERATEDMESSAGE")
            //            .Replace("###BODY###", body);

            msg.Body = body;

            var client = new SmtpClient();

            if (true)
            {
                client.Host = "smtp.gmail.com";
                client.Port = 587;
                client.UseDefaultCredentials = false;
                client.Credentials = new System.Net.NetworkCredential("yuktitests@gmail.com", "jscsitinjahhmldl"); // Enter seeders User name and password  
            }
            else
            {
                client = new SmtpClient("sg2nlvphout-v01.shr.prod.sin2.secureserver.net", 25);
            }

            client.EnableSsl = true;

            System.Threading.Tasks.Task.Run(() =>
            {
                try
                {
                    client.Send(msg);
                }
                catch (Exception ex)
                {
                   // new LoggerService().Write(ex.Message);
                }
            });
        }    
    }

    public enum EmailPriority
    {
        Urgent,
        Normal,
        Low
    }

}
